# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'echelleDesignerWindow.ui'
#
# Created: Thu Apr 03 10:01:10 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(765, 192)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBoxInputs = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxInputs.setGeometry(QtCore.QRect(10, 10, 296, 170))
        self.groupBoxInputs.setObjectName(_fromUtf8("groupBoxInputs"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxInputs)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayoutInputs = QtGui.QVBoxLayout()
        self.verticalLayoutInputs.setObjectName(_fromUtf8("verticalLayoutInputs"))
        self.gridLayoutWavelengths = QtGui.QGridLayout()
        self.gridLayoutWavelengths.setObjectName(_fromUtf8("gridLayoutWavelengths"))
        self.textLambdaMin = QtGui.QLineEdit(self.groupBoxInputs)
        self.textLambdaMin.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.textLambdaMin.setObjectName(_fromUtf8("textLambdaMin"))
        self.gridLayoutWavelengths.addWidget(self.textLambdaMin, 1, 2, 1, 1)
        self.labelLambdaMax = QtGui.QLabel(self.groupBoxInputs)
        self.labelLambdaMax.setObjectName(_fromUtf8("labelLambdaMax"))
        self.gridLayoutWavelengths.addWidget(self.labelLambdaMax, 0, 3, 1, 1)
        self.textLambdaMax = QtGui.QLineEdit(self.groupBoxInputs)
        self.textLambdaMax.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.textLambdaMax.setObjectName(_fromUtf8("textLambdaMax"))
        self.gridLayoutWavelengths.addWidget(self.textLambdaMax, 1, 3, 1, 1)
        self.labelLambdaMin = QtGui.QLabel(self.groupBoxInputs)
        self.labelLambdaMin.setObjectName(_fromUtf8("labelLambdaMin"))
        self.gridLayoutWavelengths.addWidget(self.labelLambdaMin, 0, 2, 1, 1)
        self.verticalLayoutInputs.addLayout(self.gridLayoutWavelengths)
        self.gridLayoutAngles = QtGui.QGridLayout()
        self.gridLayoutAngles.setObjectName(_fromUtf8("gridLayoutAngles"))
        self.labelOutAngle_2 = QtGui.QLabel(self.groupBoxInputs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOutAngle_2.sizePolicy().hasHeightForWidth())
        self.labelOutAngle_2.setSizePolicy(sizePolicy)
        self.labelOutAngle_2.setObjectName(_fromUtf8("labelOutAngle_2"))
        self.gridLayoutAngles.addWidget(self.labelOutAngle_2, 0, 1, 1, 1)
        self.textOutAngle = QtGui.QLineEdit(self.groupBoxInputs)
        self.textOutAngle.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.textOutAngle.setObjectName(_fromUtf8("textOutAngle"))
        self.gridLayoutAngles.addWidget(self.textOutAngle, 1, 2, 1, 1)
        self.labelOutAngle = QtGui.QLabel(self.groupBoxInputs)
        self.labelOutAngle.setObjectName(_fromUtf8("labelOutAngle"))
        self.gridLayoutAngles.addWidget(self.labelOutAngle, 0, 2, 1, 1)
        self.textInAngle = QtGui.QLineEdit(self.groupBoxInputs)
        self.textInAngle.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.textInAngle.setObjectName(_fromUtf8("textInAngle"))
        self.gridLayoutAngles.addWidget(self.textInAngle, 1, 1, 1, 1)
        self.verticalLayoutInputs.addLayout(self.gridLayoutAngles)
        self.gridLayoutGrating = QtGui.QGridLayout()
        self.gridLayoutGrating.setObjectName(_fromUtf8("gridLayoutGrating"))
        self.labelGroovesMm = QtGui.QLabel(self.groupBoxInputs)
        self.labelGroovesMm.setObjectName(_fromUtf8("labelGroovesMm"))
        self.gridLayoutGrating.addWidget(self.labelGroovesMm, 0, 0, 1, 1)
        self.labelBlaze = QtGui.QLabel(self.groupBoxInputs)
        self.labelBlaze.setObjectName(_fromUtf8("labelBlaze"))
        self.gridLayoutGrating.addWidget(self.labelBlaze, 0, 1, 1, 1)
        self.textBlaze = QtGui.QLineEdit(self.groupBoxInputs)
        self.textBlaze.setObjectName(_fromUtf8("textBlaze"))
        self.gridLayoutGrating.addWidget(self.textBlaze, 1, 1, 1, 1)
        self.textGroovesMm = QtGui.QLineEdit(self.groupBoxInputs)
        self.textGroovesMm.setObjectName(_fromUtf8("textGroovesMm"))
        self.gridLayoutGrating.addWidget(self.textGroovesMm, 1, 0, 1, 1)
        self.verticalLayoutInputs.addLayout(self.gridLayoutGrating)
        self.gridLayout_2.addLayout(self.verticalLayoutInputs, 0, 0, 1, 1)
        self.groupBoxOutputs = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxOutputs.setGeometry(QtCore.QRect(320, 10, 433, 74))
        self.groupBoxOutputs.setObjectName(_fromUtf8("groupBoxOutputs"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxOutputs)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayoutOrders = QtGui.QGridLayout()
        self.gridLayoutOrders.setObjectName(_fromUtf8("gridLayoutOrders"))
        self.labelMaxOrder = QtGui.QLabel(self.groupBoxOutputs)
        self.labelMaxOrder.setObjectName(_fromUtf8("labelMaxOrder"))
        self.gridLayoutOrders.addWidget(self.labelMaxOrder, 0, 2, 1, 1)
        self.labelMinOrder = QtGui.QLabel(self.groupBoxOutputs)
        self.labelMinOrder.setObjectName(_fromUtf8("labelMinOrder"))
        self.gridLayoutOrders.addWidget(self.labelMinOrder, 0, 1, 1, 1)
        self.labelNumberOrders = QtGui.QLabel(self.groupBoxOutputs)
        self.labelNumberOrders.setObjectName(_fromUtf8("labelNumberOrders"))
        self.gridLayoutOrders.addWidget(self.labelNumberOrders, 0, 0, 1, 1)
        self.textOrders = QtGui.QLineEdit(self.groupBoxOutputs)
        self.textOrders.setObjectName(_fromUtf8("textOrders"))
        self.gridLayoutOrders.addWidget(self.textOrders, 1, 0, 1, 1)
        self.textOrderMin = QtGui.QLineEdit(self.groupBoxOutputs)
        self.textOrderMin.setObjectName(_fromUtf8("textOrderMin"))
        self.gridLayoutOrders.addWidget(self.textOrderMin, 1, 1, 1, 1)
        self.textOrderMax = QtGui.QLineEdit(self.groupBoxOutputs)
        self.textOrderMax.setObjectName(_fromUtf8("textOrderMax"))
        self.gridLayoutOrders.addWidget(self.textOrderMax, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayoutOrders, 0, 0, 1, 1)
        self.pushButtonUpdate = QtGui.QPushButton(self.centralwidget)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(420, 90, 75, 23))
        self.pushButtonUpdate.setObjectName(_fromUtf8("pushButtonUpdate"))
        self.pushButtonSelectFile = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSelectFile.setGeometry(QtCore.QRect(330, 90, 75, 23))
        self.pushButtonSelectFile.setObjectName(_fromUtf8("pushButtonSelectFile"))
        self.labelFileName = QtGui.QLabel(self.centralwidget)
        self.labelFileName.setGeometry(QtCore.QRect(330, 120, 421, 20))
        self.labelFileName.setText(_fromUtf8(""))
        self.labelFileName.setObjectName(_fromUtf8("labelFileName"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.labelLambdaMax.setBuddy(self.textLambdaMax)
        self.labelLambdaMin.setBuddy(self.textLambdaMin)
        self.labelOutAngle_2.setBuddy(self.textInAngle)
        self.labelOutAngle.setBuddy(self.textOutAngle)
        self.labelGroovesMm.setBuddy(self.textGroovesMm)
        self.labelBlaze.setBuddy(self.textBlaze)
        self.labelMaxOrder.setBuddy(self.textOrderMax)
        self.labelMinOrder.setBuddy(self.textOrderMin)
        self.labelNumberOrders.setBuddy(self.textOrders)
        self.labelFileName.setBuddy(self.pushButtonSelectFile)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButtonUpdate, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.updateClicked)
        QtCore.QObject.connect(self.pushButtonSelectFile, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.selectFileClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textLambdaMin, self.textLambdaMax)
        MainWindow.setTabOrder(self.textLambdaMax, self.textInAngle)
        MainWindow.setTabOrder(self.textInAngle, self.textOutAngle)
        MainWindow.setTabOrder(self.textOutAngle, self.textGroovesMm)
        MainWindow.setTabOrder(self.textGroovesMm, self.textBlaze)
        MainWindow.setTabOrder(self.textBlaze, self.pushButtonSelectFile)
        MainWindow.setTabOrder(self.pushButtonSelectFile, self.pushButtonUpdate)
        MainWindow.setTabOrder(self.pushButtonUpdate, self.textOrders)
        MainWindow.setTabOrder(self.textOrders, self.textOrderMin)
        MainWindow.setTabOrder(self.textOrderMin, self.textOrderMax)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBoxInputs.setTitle(_translate("MainWindow", "Inputs", None))
        self.labelLambdaMax.setText(_translate("MainWindow", "Lambda_max [microns]", None))
        self.labelLambdaMin.setText(_translate("MainWindow", "&Lambda_min [microns]", None))
        self.labelOutAngle_2.setText(_translate("MainWindow", "in-plane angle [degrees]", None))
        self.labelOutAngle.setText(_translate("MainWindow", "out-of-plane angle [degrees]", None))
        self.labelGroovesMm.setText(_translate("MainWindow", "&grooves/mm", None))
        self.labelBlaze.setText(_translate("MainWindow", "&blaze angle [degrees]", None))
        self.groupBoxOutputs.setTitle(_translate("MainWindow", "Orders", None))
        self.labelMaxOrder.setText(_translate("MainWindow", "Maximum", None))
        self.labelMinOrder.setText(_translate("MainWindow", "Minimum", None))
        self.labelNumberOrders.setText(_translate("MainWindow", "Number", None))
        self.pushButtonUpdate.setText(_translate("MainWindow", "&Update", None))
        self.pushButtonSelectFile.setText(_translate("MainWindow", "&Select file", None))

